version: "3.8"

services:
    web:
        build: .
        container_name: funapp
        restart: always
        ports:
            - "80:80" # Только HTTP, так как SSL обрабатывает Cloudflare
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - funapp-network

networks:
    funapp-network:
        driver: bridge
